version: '3.7'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: ${POSTGRES_SERVER}
    restart: always
    environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pullstack-network
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8080:80'

    networks:
      - pullstack-network
  
networks:
  pullstack-network:
    driver: bridge
volumes:
  pg-data:
