version: '3.7'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: ${POSTGRES_SERVER}
    restart: always
    environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - oleoponto-network
  
networks:
  oleoponto-network:
    driver: bridge
volumes:
  pg-data:
